# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product_name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, choices=[('makeup', 'makeup'), ('beads', 'beads'), ('men', 'men'), ('men_acc', 'men_acc'), ('women', 'women')], max_length=20, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('color', models.CharField(blank=True, max_length=200)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Free', 'Free'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(blank=True, max_length=11, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('product_name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, choices=[('makeup', 'makeup'), ('beads', 'beads'), ('men', 'men'), ('men_acc', 'men_acc'), ('women', 'women')], max_length=20, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Free', 'Free'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=90, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sup_complains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_com', models.CharField(blank=True, max_length=254, null=True)),
                ('full_com', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='sup_complains',
            name='supp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier'),
        ),
        migrations.AddField(
            model_name='packages',
            name='supp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier'),
        ),
        migrations.AddField(
            model_name='ads',
            name='supp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier'),
        ),
    ]
