# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supp_Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product_name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, choices=[('makeup', 'makeup'), ('women', 'women'), ('men', 'men'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('color', models.CharField(blank=True, max_length=200)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='ads',
            name='supp_user',
        ),
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('makeup', 'makeup'), ('women', 'women'), ('men', 'men'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
