# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0002_auto_20180215_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='supp_ads',
            name='stats',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Free', 'Free'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('men_acc', 'men_acc'), ('beads', 'beads'), ('makeup', 'makeup'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Free', 'Free'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('men_acc', 'men_acc'), ('beads', 'beads'), ('makeup', 'makeup'), ('women', 'women')], max_length=20, null=True),
        ),
    ]
