# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0003_auto_20180215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free'), ('Gold', 'Gold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('women', 'women'), ('makeup', 'makeup'), ('men', 'men'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free'), ('Gold', 'Gold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('women', 'women'), ('makeup', 'makeup'), ('men', 'men'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
    ]
