# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0004_auto_20180216_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpresSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Free', 'Free'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Free', 'Free'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True),
        ),
    ]
