# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0005_auto_20180218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('beads', 'beads'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('beads', 'beads'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xpressoft',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
