# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0007_auto_20180219_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Free', 'Free')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('gold', 'gold')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='platinum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Platinum', 'Platinum')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='silver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Silver', 'Silver')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='packages',
            name='supp_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('women', 'women'), ('beads', 'beads'), ('men', 'men'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('women', 'women'), ('beads', 'beads'), ('men', 'men'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='packages',
        ),
    ]
