# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0008_auto_20180220_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('men', 'men'), ('women', 'women'), ('makeup', 'makeup'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Free', 'Free'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('men', 'men'), ('women', 'women'), ('makeup', 'makeup'), ('beads', 'beads')], max_length=20, null=True),
        ),
    ]
