# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0009_auto_20180220_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='silver',
            new_name='PSilver',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('beads', 'beads'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('beads', 'beads'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
    ]
