# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0010_auto_20180220_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PSilver',
            new_name='silv',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('men', 'men'), ('makeup', 'makeup'), ('women', 'women'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Free', 'Free'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('men', 'men'), ('makeup', 'makeup'), ('women', 'women'), ('beads', 'beads')], max_length=20, null=True),
        ),
    ]
