# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0011_auto_20180221_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Free', 'Free')], max_length=20, null=True)),
                ('prices', models.CharField(blank=True, max_length=11, null=True)),
                ('supp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='free',
            name='supp_user',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='supp_user',
        ),
        migrations.RemoveField(
            model_name='platinum',
            name='supp_user',
        ),
        migrations.RemoveField(
            model_name='silv',
            name='supp_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('men_acc', 'men_acc'), ('makeup', 'makeup'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('men_acc', 'men_acc'), ('makeup', 'makeup'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='free',
        ),
        migrations.DeleteModel(
            name='gold',
        ),
        migrations.DeleteModel(
            name='platinum',
        ),
        migrations.DeleteModel(
            name='silv',
        ),
    ]
