# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0012_auto_20180221_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('women', 'women'), ('men', 'men'), ('makeupArtist', 'makeupArtist'), ('hairstyle', 'hairstyle'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('women', 'women'), ('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
    ]
