# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0014_auto_20180305_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='supp_user',
        ),
        migrations.RemoveField(
            model_name='supplier_image',
            name='supp_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prices',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('men_acc', 'men_acc'), ('hairstyle', 'hairstyle'), ('women', 'women'), ('makeup', 'makeup'), ('makeupArtist', 'makeupArtist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('men_acc', 'men_acc'), ('women', 'women'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='packages',
        ),
        migrations.DeleteModel(
            name='supplier_image',
        ),
    ]
