# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0015_auto_20180307_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('makeup', 'makeup'), ('beads', 'beads'), ('men', 'men'), ('makeupArtist', 'makeupArtist'), ('women', 'women'), ('hairstyle', 'hairstyle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('makeup', 'makeup'), ('beads', 'beads'), ('men', 'men'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Free', 'Free'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
    ]
