# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0016_auto_20180307_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
        migrations.AddField(
            model_name='product',
            name='supp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='put.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('men', 'men'), ('makeup', 'makeup'), ('women', 'women'), ('hairstyle', 'hairstyle'), ('men_acc', 'men_acc'), ('makeupArtist', 'makeupArtist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('men', 'men'), ('makeup', 'makeup'), ('women', 'women'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free'), ('Gold', 'Gold')], max_length=20, null=True),
        ),
    ]
