# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0019_auto_20180308_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beads', 'Beads'), ('MakeupArtist', 'MakeupArtist'), ('Jewelry', 'Jewelry'), ('Hairstylist', 'Hairstylist'), ('Shoes', 'Shoes'), ('Watches', 'Watches'), ('WeddingWears', 'WeddingWears'), ('Bags', 'Bags'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('men_acc', 'men_acc'), ('men', 'men'), ('women', 'women'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('NoSub', 'NoSub'), ('Gold', 'Gold')], max_length=20, null=True),
        ),
    ]
