# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0020_auto_20180309_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beads', 'Beads'), ('Bags', 'Bags'), ('Watches', 'Watches'), ('MakeupArtist', 'MakeupArtist'), ('Jewelry', 'Jewelry'), ('Shoes', 'Shoes'), ('Hairstylist', 'Hairstylist'), ('WeddingWears', 'WeddingWears'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('women', 'women'), ('beads', 'beads'), ('men', 'men'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('NoSub', 'NoSub'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
    ]
