# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0021_auto_20180309_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Watches', 'Watches'), ('Beads', 'Beads'), ('MakeupArtist', 'MakeupArtist'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Hairstylist', 'Hairstylist'), ('Jewelry', 'Jewelry'), ('WeddingWears', 'WeddingWears')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men_acc', 'men_acc'), ('men', 'men'), ('makeup', 'makeup'), ('beads', 'beads'), ('women', 'women')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Free', 'Free'), ('NoSub', 'NoSub')], max_length=20, null=True),
        ),
    ]
