# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0022_auto_20180309_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Jewelry', 'Jewelry'), ('WeddingWears', 'WeddingWears'), ('Hairstylist', 'Hairstylist'), ('Watches', 'Watches'), ('MakeupArtist', 'MakeupArtist'), ('Bags', 'Bags'), ('Beads', 'Beads'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('men_acc', 'men_acc'), ('women', 'women'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('NoSub', 'NoSub'), ('Platinum', 'Platinum'), ('Free', 'Free'), ('Gold', 'Gold')], max_length=20, null=True),
        ),
    ]
