# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0024_auto_20180309_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='exp_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Jewelry', 'Jewelry'), ('Clothing', 'Clothing'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Watches', 'Watches'), ('MakeupArtist', 'MakeupArtist'), ('Hairstylist', 'Hairstylist'), ('WeddingWears', 'WeddingWears'), ('Beads', 'Beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('beads', 'beads'), ('men', 'men'), ('men_acc', 'men_acc'), ('makeup', 'makeup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('NoSub', 'NoSub'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Free', 'Free')], max_length=20, null=True),
        ),
    ]
