# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0025_auto_20180310_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Complains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Beads', 'Beads'), ('Hairstylist', 'Hairstylist'), ('MakeupArtist', 'MakeupArtist'), ('Watches', 'Watches'), ('WeddingWears', 'WeddingWears'), ('Jewelry', 'Jewelry'), ('Shoes', 'Shoes'), ('Bags', 'Bags')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('makeup', 'makeup'), ('women', 'women'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('UNAPPROVED', 'UNAPPROVED'), ('APPROVED', 'APPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='exp_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Free', 'Free'), ('Platinum', 'Platinum'), ('NoSub', 'NoSub')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sub_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
