# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0026_auto_20180318_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='con_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('MakeupArtist', 'MakeupArtist'), ('Jewelry', 'Jewelry'), ('Clothing', 'Clothing'), ('Hairstylist', 'Hairstylist'), ('WeddingWears', 'WeddingWears'), ('Bags', 'Bags'), ('Watches', 'Watches'), ('Beads', 'Beads'), ('Shoes', 'Shoes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('women', 'women'), ('men', 'men')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('Nil', 'Nil'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('NoSub', 'NoSub'), ('Silver', 'Silver'), ('Free', 'Free'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
    ]
