# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0027_auto_20180321_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='moderate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('WeddingWears', 'WeddingWears'), ('Clothing', 'Clothing'), ('Beads', 'Beads'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Hairstylist', 'Hairstylist'), ('Jewelry', 'Jewelry'), ('Watches', 'Watches'), ('MakeupArtist', 'MakeupArtist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men'), ('makeup', 'makeup'), ('men_acc', 'men_acc'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED'), ('Nil', 'Nil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('NoSub', 'NoSub'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
    ]
