# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0028_auto_20180328_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='moderate',
        ),
        migrations.AddField(
            model_name='product',
            name='moderate',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beads', 'Beads'), ('Jewelry', 'Jewelry'), ('Watches', 'Watches'), ('Hairstylist', 'Hairstylist'), ('MakeupArtist', 'MakeupArtist'), ('Shoes', 'Shoes'), ('Bags', 'Bags'), ('WeddingWears', 'WeddingWears'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('UNAPPROVED', 'UNAPPROVED'), ('APPROVED', 'APPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('NoSub', 'NoSub'), ('Silver', 'Silver'), ('Free', 'Free')], max_length=20, null=True),
        ),
    ]
