# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0029_auto_20180328_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('WeddingWears', 'WeddingWears'), ('Shoes', 'Shoes'), ('Watches', 'Watches'), ('Jewelry', 'Jewelry'), ('Bags', 'Bags'), ('Hairstylist', 'Hairstylist'), ('Clothing', 'Clothing'), ('Beads', 'Beads'), ('MakeupArtist', 'MakeupArtist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('beads', 'beads'), ('women', 'women'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED'), ('Nil', 'Nil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Free', 'Free'), ('Gold', 'Gold'), ('NoSub', 'NoSub'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
    ]
