# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0030_auto_20180413_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('WeddingWears', 'WeddingWears'), ('Bags', 'Bags'), ('Watches', 'Watches'), ('Jewelry', 'Jewelry'), ('Shoes', 'Shoes'), ('Beads', 'Beads'), ('Hairstylist', 'Hairstylist'), ('Clothing', 'Clothing'), ('MakeupArtist', 'MakeupArtist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_view',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('makeup', 'makeup'), ('women', 'women'), ('men', 'men'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Nil', 'Nil'), ('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('NoSub', 'NoSub'), ('Gold', 'Gold'), ('Free', 'Free'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
    ]
