# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0031_auto_20180413_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_visit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beads', 'Beads'), ('Jewelry', 'Jewelry'), ('Shoes', 'Shoes'), ('MakeupArtist', 'MakeupArtist'), ('Bags', 'Bags'), ('WeddingWears', 'WeddingWears'), ('Hairstylist', 'Hairstylist'), ('Watches', 'Watches'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderate',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('women', 'women'), ('makeup', 'makeup'), ('men', 'men'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('NoSub', 'NoSub'), ('Free', 'Free'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
    ]
