# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0035_auto_20180414_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Hairstylist', 'Hairstylist'), ('Bags', 'Bags'), ('Watches', 'Watches'), ('WeddingWears', 'WeddingWears'), ('Clothing', 'Clothing'), ('Jewelry', 'Jewelry'), ('Shoes', 'Shoes'), ('MakeupArtist', 'MakeupArtist'), ('Beads', 'Beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('beads', 'beads'), ('men', 'men'), ('women', 'women'), ('makeup', 'makeup'), ('men_acc', 'men_acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('UNAPPROVED', 'UNAPPROVED'), ('Nil', 'Nil'), ('APPROVED', 'APPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('NoSub', 'NoSub'), ('Free', 'Free'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store_visit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
