# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put', '0036_auto_20180414_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Watches', 'Watches'), ('Hairstylist', 'Hairstylist'), ('Beads', 'Beads'), ('MakeupArtist', 'MakeupArtist'), ('Shoes', 'Shoes'), ('Jewelry', 'Jewelry'), ('Bags', 'Bags'), ('WeddingWears', 'WeddingWears'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='moderate',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supp_ads',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men_acc', 'men_acc'), ('men', 'men'), ('makeup', 'makeup'), ('beads', 'beads')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='confirm',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('Nil', 'Nil'), ('UNAPPROVED', 'UNAPPROVED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, choices=[('NoSub', 'NoSub'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store_visit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
